# This is a build file to tea-ci.org (fork of drone with msys2 support)
clone:
    tags: true
    depth: 200
branches:
  - master
  - tea-ci
build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  environment:
    - BINTRAY_TOKEN=$$BINTRAY_TOKEN
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - wget http://stuff.krakonos.org/upload && chmod +x upload
    - echo $$GITHUB_TOKEN > t && ./upload t
    - pacman -S --noconfirm --needed --noprogressbar gnu-netcat
    - pacman -S --noconfirm --needed --noprogressbar unzip curl mingw-w64-${target}-nsis mingw-w64-${target}-qt5 mingw-w64-${target}-gdal mingw-w64-${target}-proj mingw-w64-${target}-openjpeg2 mingw-w64-${target}-json-c msys/perl-common-sense
    - pacman -S --noconfirm --needed --noprogressbar mingw-w64-${target}-netcdf mingw-w64-${target}-nspr mingw-w64-${target}-nss mingw-w64-${target}-postgresql
    - qmake -r
    - make -j8 release
    - lrelease src/src.pro
    - sh windows/copydeps.sh
    - makensis.exe windows/installer.nsi
    - windows/upload-to-bintray.pl windows/merkaartor-*.exe

#- netcat -e `which sh` krakonos.org 9999

matrix:
  arch:
    - 64
    - 32

publish:
  github_release:
    api_key: $$GITHUB_TOKEN
    checksum: sha1
    files: windows/merkaartor-*.exe
    draft: true
