sudo: required
dist: trusty
env:
    - QT=4
    - QT=5
os:
    - linux
    - osx
git:
    depth: 9999999

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/travis-linux-install.sh; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then ./ci/travis-osx-install.sh;   fi

script:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/travis-linux-script.sh; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then ./ci/travis-osx-script.sh;   fi

deploy:
    on:
        branch:
            - travis-ci
            - master
        condition: $TRAVIS_OS_NAME = osx
    provider: bintray
    file: binaries/bin/deploy.json
    user: krakonos
    key:
      secure: CMTTCxFAUirt3f+LOOC3ngJKzyqNuLO1il4Vmd8Jq5isAfiiShzs0Qj+8vvsdl7ebyVBQ5srTmwOY1z6B/Jzl5gpHPR3Y2oYt4hFaAkKU6nnlCELX7N/pS1TAXgX8NZjjod0xlfV2700eWDDBRs7gjGWQKhKzRVlMByWYeWV68c=
